name: Build & Push to GitHub Container Registry

# Controls when the action will run. 
on:

  # Git push
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu-2204:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ubuntu-systemd
          dockerfile: Dockerfile.ubuntu
          tags: 22.04,latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
  build-ubuntu-2004:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ubuntu-systemd
          dockerfile: Dockerfile.ubuntu
          tags: 20.04
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: debian-systemd
          dockerfile: Dockerfile.debian
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
